image: docker:latest

variables:
  DOCKER_TLS_CERTDIR: ''
  REGION: eu-central-1
  REPOSITORY_URL: <insert your ECR repositoryUri>

services:
  - docker:dind

before_script:
  - apk add --no-cache curl jq python py-pip gettext
  - pip install awscli

stages:
  - test
  - build
  - pull_push
  - deploy
  - smoke_test

test:
  stage: test
  image: node:12.1-alpine
  script:
    # TODO: execute the unit tests here
    - echo "No tests configured"
  except:
    - master

build:
  stage: build
  script:
    - $(aws ecr get-login --no-include-email --region $REGION)
    # TODO: implement docker build command
    # TODO: implement docker push command
  except:
    - master
