version: '3.2'
services:
  redis:
    image: redis
    ports:
      - 6379:6379

  frontend:
    build: ./app
    image: frontend
    ports:
      - 8080:8080
    environment:
      - SERVER_PORT=8080
      - REDIS_SERVER=redis
      - REDIS_PORT=6379
      - VOTE_VALUE_1=CATS
      - VOTE_VALUE_2=DOGS
    depends_on:
      - redis
