apiVersion: v1
kind: Namespace
metadata:
  name: voting
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: voting
spec:
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          # TODO: insert your own repositoryUri
          image: <your_ECR_repositoryUri>
          resources:
            limits:
              memory: '128Mi'
              cpu: '500m'
          ports:
            - containerPort: 8080
          env:
            - name: SERVER_PORT
              value: '8080'
            - name: REDIS_SERVER
              value: 'redis.voting.svc.cluster.local'
            - name: REDIS_PORT
              value: '6379'
            - name: VOTE_VALUE_1
              value: 'CATS'
            - name: VOTE_VALUE_2
              value: 'DOGS'
          imagePullPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: voting
spec:
  selector:
    app: frontend
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 8080
---
kind: ConfigMap
apiVersion: v1
metadata:
  name: redis-config
  namespace: voting
data:
  redis.conf: |
    maxmemory 2mb
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
  namespace: voting
spec:
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
        - name: redis
          image: redis
          resources:
            limits:
              memory: '128Mi'
              cpu: '500m'
          ports:
            - containerPort: 6379
          command:
            - redis-server
            - '/redis-master/redis.conf'
          volumeMounts:
            - mountPath: /redis-master
              name: config
      volumes:
        - name: config
          configMap:
            name: redis-config
---
apiVersion: v1
kind: Service
metadata:
  name: redis
  namespace: voting
spec:
  selector:
    app: redis
  ports:
    - port: 6379
---
apiVersion: v1
kind: Service
metadata:
  name: redis-monitor-svc
  namespace: voting
  labels:
    app: redis
    k8s-app: redis
  annotations:
    prometheus.io/scrape: 'true'
    prometheus.io/port: '9121'
spec:
  ports:
    - name: redis-metrics
      port: 9121
      targetPort: 9121
      protocol: TCP
  selector:
    app: redis
