apiVersion: cert-manager.io/v1alpha2
kind: ClusterIssuer
metadata:
  name: letsencrypt-production
spec:
  acme:
    # The ACME server URL
    server: https://acme-v02.api.letsencrypt.org/directory
    # Email address used for ACME registration
    email: <your-email-address>
    # Name of a secret used to store the ACME account private key
    privateKeySecretRef:
      name: letsencrypt-production
    # Enable the HTTP-01 challenge provider
    http01: {}
    dns01:
    solvers:
      - selector:
          dnsZones:
            - 'devops.senacor.com'
        dns01:
          route53:
            region: eu-central-1
            accessKeyID: <your-access-key>
            secretAccessKeySecretRef:
              name: route53-secret
              key: secret-access-key
